"""initial_revision8

Revision ID: 60a0691a4efc
Revises: 760eaa0730f7
Create Date: 2025-10-04 15:15:52.371678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a0691a4efc'
down_revision: Union[str, Sequence[str], None] = '760eaa0730f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessrequests', sa.Column('access_reason', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessrequests', 'access_reason')
    # ### end Alembic commands ###
