"""initial_revision5

Revision ID: a9a3f74b56b3
Revises: bcea76c5e6c0
Create Date: 2025-10-04 06:58:16.806666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a3f74b56b3'
down_revision: Union[str, Sequence[str], None] = 'bcea76c5e6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accessrecords_user_id_fkey'), 'accessrecords', type_='foreignkey')
    op.drop_constraint(op.f('accessrecords_secret_id_fkey'), 'accessrecords', type_='foreignkey')
    op.drop_column('accessrecords', 'user_id')
    op.drop_column('accessrecords', 'secret_id')
    op.drop_constraint(op.f('accessrequests_secret_id_fkey'), 'accessrequests', type_='foreignkey')
    op.drop_constraint(op.f('accessrequests_user_id_fkey'), 'accessrequests', type_='foreignkey')
    op.drop_column('accessrequests', 'user_id')
    op.drop_column('accessrequests', 'secret_id')
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('field', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'field')
    op.drop_column('users', 'email')
    op.add_column('accessrequests', sa.Column('secret_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('accessrequests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('accessrequests_user_id_fkey'), 'accessrequests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('accessrequests_secret_id_fkey'), 'accessrequests', 'secrets', ['secret_id'], ['id'])
    op.add_column('accessrecords', sa.Column('secret_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('accessrecords', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('accessrecords_secret_id_fkey'), 'accessrecords', 'secrets', ['secret_id'], ['id'])
    op.create_foreign_key(op.f('accessrecords_user_id_fkey'), 'accessrecords', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
