"""initial_revision9

Revision ID: c024a9d8246a
Revises: 9ac235a7eb98
Create Date: 2025-10-05 15:08:03.758142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c024a9d8246a'
down_revision: Union[str, Sequence[str], None] = '9ac235a7eb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.drop_column('users', 'field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
